import Head from 'next/head'
import Nav from '../components/Nav'
import Main from '../components/home'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Code Mode</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </Head>
    
         <Nav/> 
         <Main/>
         <Footer/>

    </>
  )
}
